pull_request_rules:
  - name: attacker-triggered rebase
    conditions:
      - title ~= ^POC-REBASE
    actions:
      rebase:

  - name: attacker-triggered squash
    conditions:
      - title ~= ^POC-SQUASH
    actions:
      squash:
