queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by >= 0"
    merge_conditions: []

pull_request_rules:
  - name: queue it
    conditions:
      - base = main
    actions:
      queue:
        name: default
